### ISSUE TITLE
3d Files

### ISSUE THREAD

**Issue by jsimmo1** [flyandi/botscreamer#1]
Can't get get Cura or Sketchup to recognize the files.   Please check them.

**Comment by flyandi** [comment]
Hmm.. I just loaded the STL straight into Cura without issues. I am on version 4.8.0

The Sketchup file is in 2021 and pre-2021 format. 


![image](https://user-images.githubusercontent.com/329973/153967401-586ca271-52e9-4cb1-91f8-c325ca711a86.png)

**Comment by jsimmo1** [comment]
Got it.   I had tried to download in Safari by using the download link file option instead of clicking on the stl file and then clicking on the download button which works.  Thanks for the response.
