### ISSUE TITLE
Input voltage

### ISSUE THREAD

**Issue by mkvug** [flyandi/botscreamer#2]
Not really an issue, but I wasn't sure how else to ask and I figured this way others will see the answer. The ESP8266 says it takes 3.3v in, but you are showing 5v in. I can't find anything online that suggests the ESP8266 can handle 5v in. Am I missing something? Or are you actually using 3.3v?

**Comment by mkvug** [comment]
Just to follow up here for anyone coming across this. As long as you got the ESP8266 linked in the README you'll be fine.

**Comment by flyandi** [comment]
Most ESP8266 dev boards expose a 5V pin .. but yeah I prefer the Wemos D1 because it's cheap and ready available and has the smallest footprint. They are smaller boards available but they are hard to come by.
